# Zensicalç‰ˆæœ¬ 0.0.8
[project]
site_name = "é™†å›½æ¾çš„ç¼–ç¨‹ç¬”è®°"
site_description = "å­¦ä¹ ç¼–ç¨‹è¿‡ç¨‹ä¸­æ•´ç†çš„ç¬”è®°é›†åˆ"
site_url = "https://luguosong.github.io/programming-notes"
site_author = "é™†å›½æ¾"
copyright = "Copyright &copy; 2025 é™†å›½æ¾"
docs_dir = "docs"
repo_url = "https://github.com/luguosong/programming-notes"
repo_name = "luguosong/programming-notes"
edit_uri = "edit/main/docs/"
# å†…å¤–è¿è¡Œåœ°å€
dev_addr = "localhost:7000"
extra_css = [
    "custom/css/font.css",
    "custom/css/custom.css",
    "custom/css/sidebar-width.css",
    "https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.11.7/viewer.min.css",
    "https://cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.min.css"
]
extra_javascript = [
    "custom/js/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
    "https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.11.7/viewer.min.js",
    "custom/js/viewer-js-init.js"
]
nav = [
    { "ä¸»é¡µ" = "index.md" },
    { "å­¦ä¹ è·¯çº¿" = [
        "roadmap/index.md",
        { "åŸºç¡€çŸ¥è¯†" = "roadmap/basic/index.md" },
        { "å‰ç«¯" = "roadmap/frontend/index.md" },
        { "Java" = "roadmap/java/index.md" },
        { "ä¸“é¢˜ç ”ç©¶" = "roadmap/topic/index.md" }
    ] },
    { "å‰ç«¯" = [
        "frontend/index.md",
        { "React" = [
            "frontend/react/index.md",
            { "åŸºç¡€" = [
                "frontend/react/basic/index.md",
                { "åŸºç¡€è¯­æ³•" = "frontend/react/basic/basic-syntax/index.md" }
            ] },
            { "å…¨å±€çŠ¶æ€ç®¡ç†" = [
                "frontend/react/global-state-management/index.md",
                { "Mobx" = "frontend/react/global-state-management/mobx/index.md" }
            ] },
            { "è·¯ç”±" = [
                "frontend/react/router/index.md",
                { "React Router" = "frontend/react/router/react-router/index.md" }
            ] }
        ] }
    ] },
    { "Java" = [
        "java/index.md"
    ] },
    { "ä¸“é¢˜ç ”ç©¶" = [
        "topic/index.md",
        { "Zensical" = [
            "topic/zensical/index.md",
            { "åŸºæœ¬ä½¿ç”¨" = "topic/zensical/basic/index.md" },
            { "æ•°å­¦å…¬å¼" = "topic/zensical/math/index.md" }
        ] }
    ] },
    { "æ•°å­¦" = [
        "math/index.md",
        { "åˆä¸­æ•°å­¦" = "math/junior-high-school-maths/index.md" }
    ] },
    { "è‹±è¯­" = [
        "english/index.md",
        { "æ–°æ¦‚å¿µè‹±è¯­" = [
            "english/new-concept-english/index.md",
            { "ç¬¬ä¸€å†Œ" = "english/new-concept-english/01/index.md" }
        ] }
    ] },
    { "æ–‡æ¡£ä¹¦ç±ç¿»è¯‘" = [
        "document-translation/index.md",
        { "Introduction to Algorithms" = [
            "document-translation/introduction-to-algorithms/index.md"
        ] },
        { "Mobx" = [
            "document-translation/mobx/index.md",
            { "MobX and React" = [
                "document-translation/the-java-tutorials/mobX-and-react/index.md",
                { "React é›†æˆ" = "document-translation/the-java-tutorials/mobX-and-react/react-integration/index.md" },
                {"ä¼˜åŒ–Reactç»„ä»¶æ¸²æŸ“"="document-translation/the-java-tutorials/mobX-and-react/react-optimizations/index.md"}
            ] },
            {"Tips & Tricks"=[
                "document-translation/the-java-tutorials/tips-tricks/index.md",
                {"å®šä¹‰æ•°æ®å­˜å‚¨"="document-translation/the-java-tutorials/tips-tricks/defining-data-stores/index.md"},
                {"ç†è§£å“åº”å¼"="document-translation/the-java-tutorials/tips-tricks/understanding-reactivity/index.md"},
                {"å­ç±»åŒ–"="document-translation/the-java-tutorials/tips-tricks/subclassing/index.md"},
                {"åˆ†æå“åº”æ€§ {ğŸš€}"="document-translation/the-java-tutorials/tips-tricks/analyzing-reactivity/index.md"}
            ]}
        ] },
        { "The Java Tutorials" = [
            "document-translation/the-java-tutorials/index.md"
        ] },
        { "Spring Start Here" = [
            "document-translation/spring-start-here/index.md"
        ] },
        { "OAuth 2 in Action" = [
            "document-translation/oauth2-in-action/index.md",
            { "åº" = "document-translation/oauth2-in-action/foreword/index.md" },
            { "å‰è¨€" = "document-translation/oauth2-in-action/preface/index.md" },
            { "å…³äºæœ¬ä¹¦" = "document-translation/oauth2-in-action/about-this-book/index.md" },
            { "èµ·æ­¥" = [
                "document-translation/oauth2-in-action/part1/index.md",
                { "1.ä»€ä¹ˆæ˜¯ OAuth 2.0ï¼Œä»¥åŠä½ ä¸ºä»€ä¹ˆéœ€è¦å…³æ³¨ï¼Ÿ" = "document-translation/oauth2-in-action/part1/01-what-is-oauth2-and-why-should-you-care/index.md" },
                { "2.OAuth ä¹‹èˆ" = "document-translation/oauth2-in-action/part1/02-the-oauth-dance/index.md" }
            ] },
            { "æ„å»º OAuth 2 ç¯å¢ƒ" = [
                "document-translation/oauth2-in-action/part2/index.md",
                { "3.æ„å»ºä¸€ä¸ªç®€å•çš„OAuthå®¢æˆ·ç«¯" = "document-translation/oauth2-in-action/part2/03-building-a-simple-oauth-client/index.md" },
                { "4.æ„å»ºä¸€ä¸ªç®€å•çš„ OAuth å—ä¿æŠ¤èµ„æº" = "document-translation/oauth2-in-action/part2/04-building-a-simple-oauth-protected-resource/index.md" },
                { "5.æ„å»ºä¸€ä¸ªç®€å•çš„ OAuth æˆæƒæœåŠ¡å™¨" = "document-translation/oauth2-in-action/part2/05-building-a-simple-oauth-authorization-server/index.md" },
                { "6.çœŸå®ä¸–ç•Œä¸­çš„ OAuth 2.0" = "document-translation/oauth2-in-action/part2/06-oauth-2-in-the-real-world/index.md" }
            ] },
            { "OAuth 2 çš„å®ç°ä¸æ¼æ´" = [
                "document-translation/oauth2-in-action/part3/index.md",
                { "7.å¸¸è§å®¢æˆ·ç«¯æ¼æ´" = "document-translation/oauth2-in-action/part3/07-common-client-vulnerabilities/index.md" },
                { "8.å¸¸è§çš„å—ä¿æŠ¤èµ„æºæ¼æ´" = "document-translation/oauth2-in-action/part3/08-common-protected-resources-vulnerabilities/index.md" },
                { "9.å¸¸è§çš„æˆæƒæœåŠ¡å™¨æ¼æ´" = "document-translation/oauth2-in-action/part3/09-common-authorization-server-vulnerabilities/index.md" },
                { "10.å¸¸è§çš„ OAuth ä»¤ç‰Œæ¼æ´" = "document-translation/oauth2-in-action/part3/10-common-oauth-token-vulnerabilities/index.md" }
            ] },
            { "æ·±å…¥æ‹“å±• OAuth" = [
                "document-translation/oauth2-in-action/part4/index.md",
                { "11.OAuth ä»¤ç‰Œ" = "document-translation/oauth2-in-action/part4/11-oauth-tokens/index.md" },
                { "12.åŠ¨æ€å®¢æˆ·ç«¯æ³¨å†Œ" = "document-translation/oauth2-in-action/part4/12-dynamic-client-registration/index.md" },
                { "13.ä½¿ç”¨ OAuth 2.0 è¿›è¡Œç”¨æˆ·è®¤è¯" = "document-translation/oauth2-in-action/part4/13-user-authentication-with-oauth2/index.md" },
                { "14.åŸºäº OAuth 2.0 çš„åè®®ä¸é…ç½®æ–‡ä»¶" = "document-translation/oauth2-in-action/part4/14-protocols-and-profiles-using-oauth2/index.md" },
                { "15.bearer ä»¤ç‰Œä»¥å¤–çš„é€‰æ‹©" = "document-translation/oauth2-in-action/part4/15-beyond-bearer-tokens/index.md" },
                { "16.æ€»ç»“ä¸ç»“è¯­" = "document-translation/oauth2-in-action/part4/16-summary-and-conclusions/index.md" }
            ] },
            { "é™„å½• Aï¼šæˆ‘ä»¬çš„ä»£ç æ¡†æ¶ç®€ä»‹" = "document-translation/oauth2-in-action/appendix-a/index.md" },
            { "é™„å½• Bï¼šæ‰©å±•ä»£ç æ¸…å•" = "document-translation/oauth2-in-action/appendix-b/index.md" }
        ] },
        { "Spring Security in Action 2" = [
            "document-translation/spring-security-in-action2/index.md",
            { "Spring Securityå…¥é—¨" = [
                "document-translation/spring-security-in-action2/part1/index.md",
                { "1.å®‰å…¨ç°çŠ¶" = "document-translation/spring-security-in-action2/part1/01-security-today/index.md" },
                { "2.Spring Security å…¥é—¨" = "document-translation/spring-security-in-action2/part1/02-hello/index.md" }
            ] },
            { "é…ç½®èº«ä»½è®¤è¯" = [
                "document-translation/spring-security-in-action2/part2/index.md",
                { "3.ç”¨æˆ·ç®¡ç†" = "document-translation/spring-security-in-action2/part2/03-managing-users/index.md" },
                { "4.å¯†ç ç®¡ç†" = "document-translation/spring-security-in-action2/part2/04-managing-passwords/index.md" },
                { "5.ä¸€ä¸ªWebåº”ç”¨çš„å®‰å…¨æ€§å§‹äºè¿‡æ»¤å™¨" = "document-translation/spring-security-in-action2/part2/05-begins-with-filters/index.md" },
                { "6.å®ç°èº«ä»½è®¤è¯" = "document-translation/spring-security-in-action2/part2/06-implementing-authentications/index.md" }
            ] },
            { "é…ç½®æˆæƒ" = [
                "document-translation/spring-security-in-action2/part3/index.md",
                { "7.é…ç½®ç«¯ç‚¹çº§æˆæƒï¼šé™åˆ¶è®¿é—®" = "document-translation/spring-security-in-action2/part3/07-authorization-restricting-access/index.md" },
                { "8.é…ç½®ç«¯ç‚¹çº§æˆæƒï¼šåº”ç”¨è®¿é—®é™åˆ¶" = "document-translation/spring-security-in-action2/part3/08-authorization-applying-restrictions/index.md" },
                { "9.é…ç½®CSRFé˜²æŠ¤" = "document-translation/spring-security-in-action2/part3/09-configuring-csrf-protection/index.md" },
                { "10.é…ç½®CORS" = "document-translation/spring-security-in-action2/part3/10-configuring-cors/index.md" },
                { "11.åœ¨æ–¹æ³•çº§åˆ«å®ç°æˆæƒ" = "document-translation/spring-security-in-action2/part3/11-implementing-authorization-at-the-method-level/index.md" },
                { "12.åœ¨æ–¹æ³•çº§åˆ«å®ç°è¿‡æ»¤" = "document-translation/spring-security-in-action2/part3/12-implementing-filtering-at-the-method-level/index.md" }
            ] },
            { "å®ç°OAuth 2ä¸OpenID Connect" = [
                "document-translation/spring-security-in-action2/part4/index.md",
                { "13.OAuth 2å’ŒOpenID Connectæ˜¯ä»€ä¹ˆ" = "document-translation/spring-security-in-action2/part4/13-what-are-oauth2-and-openid-connect/index.md" },
                { "14.å®ç°OAuth 2æˆæƒæœåŠ¡å™¨" = "document-translation/spring-security-in-action2/part4/14-implementing-an-oauth2-authorization-server/index.md" },
                { "15.å®ç°OAuth2èµ„æºæœåŠ¡å™¨" = "document-translation/spring-security-in-action2/part4/15-implementing-an-oauth2-resource-server/index.md" },
                { "16.å®ç°OAuth2å®¢æˆ·ç«¯" = "document-translation/spring-security-in-action2/part4/16-implementing-an-oAuth2-client/index.md" }
            ] },
            { "å“åº”å¼" = [
                "document-translation/spring-security-in-action2/part5/index.md",
                { "17.åœ¨å“åº”å¼åº”ç”¨ä¸­å®ç°å®‰å…¨æ€§" = "document-translation/spring-security-in-action2/part5/17-implementing-security-in-reactive-applications/index.md" }
            ] },
            { "æµ‹è¯•å®‰å…¨é…ç½®" = [
                "document-translation/spring-security-in-action2/part6/index.md",
                { "18.æµ‹è¯•å®‰å…¨é…ç½®" = "document-translation/spring-security-in-action2/part6/18-testing-security-configurations/index.md" }
            ] }
        ] },
        { "Spring Security-6.5.7" = [
            "document-translation/spring-security-567/index.md",
            { "Servletåº”ç”¨" = [
                "document-translation/spring-security-567/servlet-applications/index.md",
                { "OAuth2" = [
                    "document-translation/spring-security-567/servlet-applications/oauth2/index.md"
                ] }
            ] }
        ] },
        { "Spring Authorization Server-1.5.3" = [
            "document-translation/spring-authorization-server-153/index.md",
            { "Spring Authorization Server è¿ç§»è‡³ Spring Security 7.0" = "document-translation/spring-authorization-server-153/moving-to-spring-security-70/index.md" },
            { "æ¦‚è¿°" = "document-translation/spring-authorization-server-153/01-overview/index.md" },
            { "è·å–å¸®åŠ©" = "document-translation/spring-authorization-server-153/02-getting-help/index.md" },
            { "å…¥é—¨" = "document-translation/spring-authorization-server-153/03-getting-started/index.md" },
            { "é…ç½®" = "document-translation/spring-authorization-server-153/04-configuration-model/index.md" },
            { "æ ¸å¿ƒæ¨¡å‹/ç»„ä»¶" = "document-translation/spring-authorization-server-153/05-core-model-components/index.md" },
            { "åè®®ç«¯ç‚¹" = "document-translation/spring-authorization-server-153/06-protocol-endpoints/index.md" },
            { "æ“ä½œæŒ‡å—" = [
                "document-translation/spring-authorization-server-153/07-how-to-guides/index.md",
                { "åœ¨å•é¡µåº”ç”¨ï¼ˆSPAï¼‰ä¸­ä½¿ç”¨PKCEè¿›è¡Œèº«ä»½è®¤è¯" = "document-translation/spring-authorization-server-153/07-how-to-guides/01-authenticate-using-a-single-page-application-with-pkce/index.md" },
                { "ä½¿ç”¨ç¤¾äº¤è´¦å·ç™»å½•è¿›è¡Œèº«ä»½éªŒè¯" = "document-translation/spring-authorization-server-153/07-how-to-guides/02-authenticate-using-social-login/index.md" },
                { "å®ç°æ‰©å±•æˆæƒè®¸å¯ç±»å‹" = "document-translation/spring-authorization-server-153/07-how-to-guides/03-implement-an-extension-authorization-grant-type/index.md" },
                { "å®ç°å¤šç§Ÿæˆ·(Multitenancy)" = "document-translation/spring-authorization-server-153/07-how-to-guides/04-implement-multitenancy/index.md" },
                { "è‡ªå®šä¹‰OpenID Connect 1.0çš„UserInfoå“åº”" = "document-translation/spring-authorization-server-153/07-how-to-guides/05-customize-the-oidc-userinfo-response/index.md" },
                { "é€šè¿‡JPAå®ç°æ ¸å¿ƒæœåŠ¡" = "document-translation/spring-authorization-server-153/07-how-to-guides/06-implement-core-services-with-jpa/index.md" },
                { "ç”¨Rediså®ç°æ ¸å¿ƒæœåŠ¡" = "document-translation/spring-authorization-server-153/07-how-to-guides/07-implement-core-services-with-redis/index.md" },
                { "åœ¨JWTè®¿é—®ä»¤ç‰Œä¸­å°†æƒé™ä½œä¸ºè‡ªå®šä¹‰å£°æ˜æ·»åŠ " = "document-translation/spring-authorization-server-153/07-how-to-guides/08-add-authorities-as-custom-claims-in-jwt-access-tokens/index.md" },
                { "åŠ¨æ€æ³¨å†Œå®¢æˆ·ç«¯" = "document-translation/spring-authorization-server-153/07-how-to-guides/09-register-a-client-dynamically/index.md" }
            ] }
        ] },
        { "Real World Cryptography" = [
            "document-translation/real-world-cryptography/index.md"
        ] },
        { "Java Cryptography: Tools and Techniques" = [
            "document-translation/java-cryptography-tools-and-techniques/index.md",
            { "1.å…¥é—¨æ¦‚è§ˆ" = "document-translation/java-cryptography-tools-and-techniques/01-getting-started-an-overview/index.md" }
        ] },
        { "Open Design Alliance" = [
            "document-translation/opendesign/index.md",
            { "Open Cloud" = [
                "document-translation/opendesign/open-cloud/index.md",
                { "Drawing inWEB" = [
                    "document-translation/opendesign/open-cloud/drawing-inweb/index.md",
                    { "æ¦‚è¿°" = "document-translation/opendesign/open-cloud/drawing-inweb/overview/index.md" },
                    { "å®‰è£…" = "document-translation/opendesign/open-cloud/drawing-inweb/installation/index.md" },
                    { "ä»‹ç»" = [
                        "document-translation/opendesign/open-cloud/drawing-inweb/introduction/index.md",
                        { "åˆ›å»ºä½ çš„ç¬¬ä¸€ä¸ª DrawingWeb SDK åº”ç”¨" = "document-translation/opendesign/open-cloud/drawing-inweb/introduction/first-app/index.md" }
                    ] }
                ] }
            ] }
        ] }
    ] }
]

[project.theme]
variant = "modern"
language = "zh"
logo = "assert/logo.gif"
favicon = "assert/logo.gif"
custom_dir = "overrides"
icon.repo = "fontawesome/brands/github"
features = [
    # å½“å¯ç”¨å³æ—¶å¯¼èˆªæ—¶ï¼Œæ‰€æœ‰å†…éƒ¨é“¾æ¥çš„ç‚¹å‡»æ“ä½œéƒ½ä¼šè¢«æ‹¦æˆªï¼Œå¹¶é€šè¿‡XHRåˆ†å‘è¯·æ±‚ï¼Œè€Œä¸ä¼šå®Œå…¨é‡æ–°åŠ è½½é¡µé¢ã€‚
    "navigation.instant",
    # å½“ç”¨æˆ·å°†é¼ æ ‡æ‚¬åœåœ¨é“¾æ¥ä¸Šæ—¶å°±ä¼šå¼€å§‹è·å–é¡µé¢å†…å®¹ã€‚è¿™ä¼šé™ä½ç”¨æˆ·æ„ŸçŸ¥çš„åŠ è½½æ—¶é—´ï¼Œç‰¹åˆ«æ˜¯åœ¨æ…¢é€Ÿç½‘ç»œç¯å¢ƒä¸‹ï¼Œå› ä¸ºå¯¼èˆªåé¡µé¢å°†ä¼šç«‹å³å¯ç”¨ã€‚
    "navigation.instant.prefetch",
    # è¿›åº¦æŒ‡ç¤ºå™¨ã€‚å®ƒä¼šæ˜¾ç¤ºåœ¨é¡µé¢é¡¶éƒ¨ï¼Œç­‰é¡µé¢å®Œå…¨åŠ è½½åå†éšè—ã€‚
    "navigation.instant.progress",
    # é¡¶å±‚æ¿å—ä¼šåœ¨è§†å£å®½åº¦å¤§äº1220pxæ—¶ä»¥èœå•çš„å½¢å¼æ˜¾ç¤ºåœ¨é¡µçœ‰ä¸‹æ–¹ï¼Œè€Œåœ¨ç§»åŠ¨ç«¯åˆ™ä¿æŒåŸæ ·ã€‚
    "navigation.tabs",
    # æ–‡æ¡£é¢åŒ…å±‘
    "navigation.path",
    # å½“å¯ç”¨è£å‰ªåŠŸèƒ½æ—¶ï¼Œåªæœ‰å¯è§çš„å¯¼èˆªé¡¹ä¼šè¢«æ¸²æŸ“åˆ° HTML ä¸­ï¼Œä»è€Œä½¿æ„å»ºåçš„ç½‘ç«™ä½“ç§¯å‡å°‘ 33% æˆ–æ›´å¤šã€‚
    "navigation.prune",
    # å¯ç”¨ç« èŠ‚ç´¢å¼•é¡µåï¼Œå¯ä»¥å°†æ–‡æ¡£ç›´æ¥é™„åŠ åˆ°å„ä¸ªç« èŠ‚ï¼Œè¿™å¯¹äºæä¾›æ¦‚è§ˆé¡µé¢å°¤å…¶æœ‰ç”¨ã€‚
    "navigation.indexes",
    # å½“å¯ç”¨ç›®å½•çš„é”šç‚¹è·ŸéšåŠŸèƒ½æ—¶ï¼Œä¾§è¾¹æ ä¼šè‡ªåŠ¨æ»šåŠ¨ï¼Œç¡®ä¿å½“å‰æ¿€æ´»çš„é”šç‚¹å§‹ç»ˆå¯è§ã€‚
    "toc.follow",
    # è¿”å›é¡¶éƒ¨æŒ‰é’®
    "navigation.top",
    # è·³è½¬åˆ°ç›®æ ‡é¡µåï¼Œæœç´¢å…³é”®è¯é«˜äº®
    "search.highlight",
    # é¡µè„šå¯ä»¥åŒ…å«å½“å‰é¡µé¢çš„ä¸Šä¸€é¡µå’Œä¸‹ä¸€é¡µé“¾æ¥ã€‚
    "navigation.footer",
    "navigation.prune",
    # ç¼–è¾‘é¡µé¢æŒ‰é’®
    "content.action.edit",
    # æŸ¥çœ‹é¡µé¢ä»£ç æŒ‰é’®
    "content.action.view",
    "content.code.copy",
    "content.code.select",
    "content.code.annotate",
    "content.tooltips"
]

[project.extra]
generator = false

# ç¤¾äº¤é“¾æ¥
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/luguosong"
name = "GitHub"

[[project.extra.social]]
icon = "simple/wechat"
link = "https://cdn.jsdelivr.net/gh/luguosong/images@master/blog-img/202404272008366.png"
name = "å¾®ä¿¡"

# ä¸»é¢˜é…è‰²æ–¹æ¡ˆ
[[project.theme.palette]]
scheme = "slate"
accent = "blue"
primary = "blue"
toggle.icon = "lucide/moon"
toggle.name = "åˆ‡æ¢åˆ°æµ…è‰²æ¨¡å¼"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
accent = "orange"
primary = "orange"
toggle.name = "åˆ‡æ¢åˆ°æ·±è‰²æ¨¡å¼"

# æ‰©å±•ç¨‹åº
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]


