# Zensical版本 0.0.8
[project]
site_name = "陆国松的编程笔记"
site_description = "学习编程过程中整理的笔记集合"
site_url = "https://luguosong.github.io/programming-notes"
site_author = "陆国松"
copyright = "Copyright &copy; 2025 陆国松"
docs_dir = "code"
repo_url = "https://github.com/luguosong/programming-notes"
repo_name = "luguosong/programming-notes"
edit_uri = "edit/main/code/"
# 内外运行地址
dev_addr = "localhost:7000"
extra_css = [
    "custom/css/font.css",
    "custom/css/custom.css",
    "custom/css/sidebar-width.css",
    "https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.11.7/viewer.min.css"
]
extra_javascript = [
    "custom/js/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
    "https://cdnjs.cloudflare.com/ajax/libs/viewerjs/1.11.7/viewer.min.js",
    "custom/js/viewer-js-init.js"
]
nav = [
    { "主页" = "index.md" },
    { "学习路线" = "roadmap.md" },
    { "专题研究" = [
        "topic/index.md",
        { "Zensical" = [
            "topic/zensical/index.md",
            { "基本使用" = "topic/zensical/basic/index.md" },
            { "数学公式" = "topic/zensical/math/index.md" }
        ] }
    ] },
    { "文档书籍翻译" = [
        "document-translation/index.md",
        { "Introduction to Algorithms" = [
            "document-translation/introduction-to-algorithms/index.md"
        ] },
        { "The Java Tutorials" = [
            "document-translation/the-java-tutorials/index.md"
        ] },
        { "Spring Start Here" = [
            "document-translation/spring-start-here/index.md"
        ] },
        { "Spring Security in Action 2" = [
            "document-translation/spring-security-in-action2/index.md",
            { "Spring Security入门" = [
                "document-translation/spring-security-in-action2/part1/index.md",
                { "1.安全现状" = "document-translation/spring-security-in-action2/part1/01-security-today/index.md" },
                { "2.Spring Security 入门" = "document-translation/spring-security-in-action2/part1/02-hello/index.md" }
            ] },
            { "配置身份认证" = [
                "document-translation/spring-security-in-action2/part2/index.md",
                { "3.用户管理" = "document-translation/spring-security-in-action2/part2/03-managing-users/index.md" },
                { "4.密码管理" = "document-translation/spring-security-in-action2/part2/04-managing-passwords/index.md" },
                { "5.一个Web应用的安全性始于过滤器" = "document-translation/spring-security-in-action2/part2/05-begins-with-filters/index.md" },
                { "6.实现身份认证" = "document-translation/spring-security-in-action2/part2/06-implementing-authentications/index.md" }
            ] },
            { "配置授权" = [
                "document-translation/spring-security-in-action2/part3/index.md",
                { "7.配置端点级授权：限制访问" = "document-translation/spring-security-in-action2/part3/07-authorization-restricting-access/index.md" },
                { "8.配置端点级授权：应用访问限制" = "document-translation/spring-security-in-action2/part3/08-authorization-applying-restrictions/index.md" },
                { "9.配置CSRF防护" = "document-translation/spring-security-in-action2/part3/09-configuring-csrf-protection/index.md" },
                { "10.配置CORS" = "document-translation/spring-security-in-action2/part3/10-configuring-cors/index.md" },
                { "11.在方法级别实现授权" = "document-translation/spring-security-in-action2/part3/11-implementing-authorization-at-the-method-level/index.md" },
                { "12.在方法级别实现过滤" = "document-translation/spring-security-in-action2/part3/12-implementing-filtering-at-the-method-level/index.md" }
            ] },
            { "实现OAuth 2与OpenID Connect" = [
                "document-translation/spring-security-in-action2/part4/index.md",
                { "13.OAuth 2和OpenID Connect是什么" = "document-translation/spring-security-in-action2/part4/13-what-are-oauth2-and-openid-connect/index.md" },
                { "14.实现OAuth 2授权服务器" = "document-translation/spring-security-in-action2/part4/14-implementing-an-oauth2-authorization-server/index.md" },
                { "15.实现OAuth2资源服务器" = "document-translation/spring-security-in-action2/part4/15-implementing-an-oauth2-resource-server/index.md" },
                { "16.实现OAuth2客户端" = "document-translation/spring-security-in-action2/part4/16-implementing-an-oAuth2-client/index.md" }
            ] },
            { "响应式" = [
                "document-translation/spring-security-in-action2/part5/index.md",
                { "17.在响应式应用中实现安全性" = "document-translation/spring-security-in-action2/part5/17-implementing-security-in-reactive-applications/index.md" }
            ] },
            { "测试安全配置" = [
                "document-translation/spring-security-in-action2/part6/index.md",
                { "18.测试安全配置" = "document-translation/spring-security-in-action2/part6/18-testing-security-configurations/index.md" }
            ] }
        ] },
        { "Spring Security-6.5.7" = [
            "document-translation/spring-security-567/index.md",
            { "Servlet应用" = [
                "document-translation/spring-security-567/servlet-applications/index.md",
                { "OAuth2" = [
                    "document-translation/spring-security-567/servlet-applications/oauth2/index.md"
                ] }
            ] }
        ] },
        { "Spring Authorization Server-1.5.3" = [
            "document-translation/spring-authorization-server-153/index.md",
            { "Spring Authorization Server 迁移至 Spring Security 7.0" = "document-translation/spring-authorization-server-153/moving-to-spring-security-70/index.md" },
            { "概述" = "document-translation/spring-authorization-server-153/01-overview/index.md" },
            { "获取帮助" = "document-translation/spring-authorization-server-153/02-getting-help/index.md" },
            { "入门" = "document-translation/spring-authorization-server-153/03-getting-started/index.md" },
            { "配置" = "document-translation/spring-authorization-server-153/04-configuration-model/index.md" },
            { "核心模型/组件" = "document-translation/spring-authorization-server-153/05-core-model-components/index.md" },
            { "协议端点" = "document-translation/spring-authorization-server-153/06-protocol-endpoints/index.md" },
            { "操作指南" = [
                "document-translation/spring-authorization-server-153/07-how-to-guides/index.md",
                {"在单页应用（SPA）中使用PKCE进行身份认证" = "document-translation/spring-authorization-server-153/07-how-to-guides/01-authenticate-using-a-single-page-application-with-pkce/index.md"},
                {"使用社交账号登录进行身份验证"="document-translation/spring-authorization-server-153/07-how-to-guides/02-authenticate-using-social-login/index.md"},
                {"实现扩展授权许可类型"="document-translation/spring-authorization-server-153/07-how-to-guides/03-implement-an-extension-authorization-grant-type/index.md"},
                {"实现多租户(Multitenancy)"="document-translation/spring-authorization-server-153/07-how-to-guides/04-implement-multitenancy/index.md"},
                {"自定义OpenID Connect 1.0的UserInfo响应"="document-translation/spring-authorization-server-153/07-how-to-guides/05-customize-the-oidc-userinfo-response/index.md"},
                {"通过JPA实现核心服务"="document-translation/spring-authorization-server-153/07-how-to-guides/06-implement-core-services-with-jpa/index.md"},
                {"用Redis实现核心服务"="document-translation/spring-authorization-server-153/07-how-to-guides/07-implement-core-services-with-redis/index.md"},
                {"在JWT访问令牌中将权限作为自定义声明添加"="document-translation/spring-authorization-server-153/07-how-to-guides/08-add-authorities-as-custom-claims-in-jwt-access-tokens/index.md"},
                {"动态注册客户端"="document-translation/spring-authorization-server-153/07-how-to-guides/09-register-a-client-dynamically/index.md"}
            ] }
        ] },
        { "Real World Cryptography" = [
            "document-translation/real-world-cryptography/index.md"
        ] },
        { "Java Cryptography: Tools and Techniques" = [
            "document-translation/java-cryptography-tools-and-techniques/index.md",
            { "1.入门概览" = "document-translation/java-cryptography-tools-and-techniques/01-getting-started-an-overview/index.md" }
        ] }
    ] },
]

[project.theme]
variant = "modern"
language = "zh"
logo = "assert/logo.gif"
favicon = "assert/logo.gif"
custom_dir = "overrides"
icon.repo = "fontawesome/brands/github"
features = [
    # 当启用即时导航时，所有内部链接的点击操作都会被拦截，并通过XHR分发请求，而不会完全重新加载页面。
    "navigation.instant",
    # 当用户将鼠标悬停在链接上时就会开始获取页面内容。这会降低用户感知的加载时间，特别是在慢速网络环境下，因为导航后页面将会立即可用。
    "navigation.instant.prefetch",
    # 进度指示器。它会显示在页面顶部，等页面完全加载后再隐藏。
    "navigation.instant.progress",
    # 顶层板块会在视口宽度大于1220px时以菜单的形式显示在页眉下方，而在移动端则保持原样。
    "navigation.tabs",
    # 文档面包屑
    "navigation.path",
    # 当启用裁剪功能时，只有可见的导航项会被渲染到 HTML 中，从而使构建后的网站体积减少 33% 或更多。
    "navigation.prune",
    # 启用章节索引页后，可以将文档直接附加到各个章节，这对于提供概览页面尤其有用。
    "navigation.indexes",
    # 当启用目录的锚点跟随功能时，侧边栏会自动滚动，确保当前激活的锚点始终可见。
    "toc.follow",
    # 返回顶部按钮
    "navigation.top",
    # 跳转到目标页后，搜索关键词高亮
    "search.highlight",
    # 页脚可以包含当前页面的上一页和下一页链接。
    "navigation.footer",
    "navigation.prune",
    # 编辑页面按钮
    "content.action.edit",
    # 查看页面代码按钮
    "content.action.view",
    "content.code.copy",
    "content.code.select",
    "content.code.annotate",
    "content.tooltips"
]

[project.extra]
generator = false

# 社交链接
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/luguosong"
name = "GitHub"

[[project.extra.social]]
icon = "simple/wechat"
link = "https://cdn.jsdelivr.net/gh/luguosong/images@master/blog-img/202404272008366.png"
name = "微信"

# 主题配色方案
[[project.theme.palette]]
scheme = "slate"
accent = "blue"
primary = "blue"
toggle.icon = "lucide/moon"
toggle.name = "切换到浅色模式"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
accent = "orange"
primary = "orange"
toggle.name = "切换到深色模式"

# 扩展程序
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.def_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]


